### ISSUE TITLE
Create a new zcap context

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/zcapld#55]
The following proof/capability is being compacted into the security context:

https://github.com/digitalbazaar/zcapld/blob/master/lib/CapabilityInvocation.js#L112-L114

**NOTE:** `url` may be an object here, and is an object in this case.
https://github.com/digitalbazaar/zcapld/blob/master/lib/utils.js#L150

The compaction results in `proof.type === 'sec:Ed25519Signature2020'` which causes a failure to locate the suite.

```
{
  '@context': [
    'https://w3id.org/security/v2',
    'https://w3id.org/security/suites/ed25519-2020/v1'
  ],
  id: 'urn:zcap:6fS5PurXq4L3GXpQZoYYa8',
  controller: 'did:key:z6MksNZwi2r6Qxjt3MYLrrZ44gs2fauzgv1dk4E372bNVjtc',
  allowedAction: 'write',
  parentCapability: 'https://localhost:51443/billing-scopes/YCx3DeDUmY2zVRuB1rAyfZ/subscriptions/Ti9mWFSRHKL7zTc6KanfrV/items',
  invocationTarget: 'urn:zcap:root:https%3A%2F%2Flocalhost%3A51443%2Fbilling-scopes%2FYCx3DeDUmY2zVRuB1rAyfZ%2Fsubscriptions%2FTi9mWFSRHKL7zTc6KanfrV%2Fitems',
  proof: {
    type: 'Ed25519Signature2020',
    created: '2021-04-06T21:42:00Z',
    verificationMethod: 'did:key:z6MkfzWk1nzHNXSCtRK1jQrnR5oweC52jUsWkTYDhpETjrGs#z6MkfzWk1nzHNXSCtRK1jQrnR5oweC52jUsWkTYDhpETjrGs',
    proofPurpose: 'capabilityDelegation',
    capabilityChain: [
      'https://localhost:51443/billing-scopes/YCx3DeDUmY2zVRuB1rAyfZ/subscriptions/Ti9mWFSRHKL7zTc6KanfrV/items'
    ],
    proofValue: 'z4JruzqWLi2Qt5QzeJBmkZcx5ATrfMRU1DEuyg3nD9i7iCNTqCNrge3ZcV8soHqTyZjbLYr9b2cRaR14qnee8A735'
  }
}
```

**EDIT**: I'm working around this presently by simply returning the document as is without the `compact` operation.

**Comment by dlongley** [comment]
So this is happening because we fail the check we do before compaction -- which is to make sure the `@context` is a direct match for the `security/v2` context:

https://github.com/digitalbazaar/zcapld/blob/ab2e657d9aa1ba91bc80f97cd14eb5ac6f94384a/lib/utils.js#L143

We can't change this to just look for its appearance in a context array (which is what we have here as input) because the `security/v2` context was created before term definition protection was invented and its terms could be overwritten.

I think the solution to this is to look for a new zcap context that uses protected term definitions for the required zcap terms -- and then look for this context in the `@context` value of the zcap (where we can accept a direct match OR it can be an element of an array -- since its terms will be protected). Then we can require that context to be present and not do *any* compaction at all -- with an option for custom contexts to be used as overrides for advanced use cases.

**Comment by dlongley** [comment]
> I'm working around this presently by simply returning the document as is without the compact operation.

If we need an immediate workaround, we should temporarily allow extra safe values, such as the context in the example here. We should not just skip compaction because that introduces a security hole.

**Comment by mattcollier** [comment]
A temporary fix landed for this: https://github.com/digitalbazaar/zcapld/pull/56.  The long term solution is to develop a new zcap context and use that in place of `SECURITY_CONTEXT_V2_URL`.  Going to change the title of this issue to reflect that need and leave this open.

**Comment by mattcollier** [comment]
This landed: https://github.com/digitalbazaar/zcapld/blob/main/CHANGELOG.md#400---2021-04-26
